name: "Setup Node Environment"
description: "Sets up Node.js, installs dependencies, and caches node_modules"
inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "18"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci
      shell: bash
