name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  call-reusable-ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      node-version: "20"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}   # ✅ now valid
